package Modelo;

public enum ModelosCarro {
    
    //AGRALE
    MARRUA(1, "MARRUA"), 
    //Aston Martin
    DB9_VOLANTE(2, "DB9_VOLANTE"), DBS_COUPE(2, "DBS_COUPE"), DBS_VOLANTE(2, "DBS_VOLANTE"),
    RAPIDE(2, "RAPIDE"), V12_VANTAGE_COUPE(2, "V12_VANTAGE_COUPE"), V8_VANTAGE_COUPE(2, "V8_VANTAGE_COUPE"),
    V8_VANTAGE_ROADSTER(2, "V8_VANTAGE_ROADSTER"), VIRAGE(2, "VIRAGE"), 
    //AUDI
    A1(3, "A1"), A3_SEDAN(3, "A3_SEDAN"), A4(3, "A4"), A7(3, "A7"), A8(3, "A8"), Q3(3, "Q3"), Q5(3, "Q5"), 
    Q7(3, "Q7"), R8(3, "R8"), R8_GT(3, "R8_GT"), TT_COUPE(3, "TT_COUPE"), TT_ROADSTER(3, "TT_ROADSTER"),
    //BENTLEY
    CONTINENTAL_FLYING_SPUR(4, "CONTINENTAL_FLYING_SPUR"), 
    CONTINENTAL_SUPERSPORTS_COUPÉ(4, "CONTINENTAL_SUPERSPORTS_COUPÉ"),
    //BMW
    SERIE_1(5, "SERIE_1"), SERIE_3_M3(5, "SERIE_3_M3"), SERIE_5_GRAN_TURISMO(5, "SERIE_5_GRAN_TURISMO"), SERIE_7(5, "SERIE_7"), X1(5, "X1"), X3(5, "X3"),
    X5(5, "X5"), X6(5, "X6"), Z4_ROADSTER(5, "Z4_ROADSTER"), I3(5, "I3"),
    //CHANGAN
    CARGO(6, "CARGO"), FAMILY(6, "FAMILY"), UTILITY(6, "UTILITY"), CHERY(6, "CHERY"), CELER_HATCH(6, "CELER_HATCH"), CELER_SEDAN(6, "CELER_SEDAN"),
    CIELO_HATCH(6, "CIELO_HATCH"), CIELO_SEDAN(6, "CIELO_SEDAN"), FACE(6, "FACE"), QQ(6, "QQ"), S_18(6, "S_18"), TIGGO(6, "TIGGO"),
    //CHEVROLET
    AGILE(7, "AGILE"), ASTRA_HATCH(7, "ASTRA_HATCH"), ASTRA_SEDAN(7, "ASTRA_SEDAN"), BLAZER(7, "BLAZER"), CAMARO(7, "CAMARO"), CAPTIVA(7, "CAPTIVA"),
    CELTA(7, "CELTA"), CLASSIC(7, "CLASSIC"), COBALT(7, "COBALT"), CORSA_HATCH(7, "CORSA_HATCH"), CRUZE(7, "CRUZE"), SPORT6(7 , "SPORT6"),
    MALIBU(7, "MALIBU"), MERIVA(7, "MERIVA"), MONTANA(7, "MONTANA"), OMEGA(7, "OMEGA"), ONIX(7 , "ONIX"), PRISMA(7, "PRISMA"), S10(7, "S10"),
    SONIC(7, "SONIC"), SPIN(7, "SPIN"), TRACKER(7, "TRACKER"), TRAILBLAZER(7, "TRAILBLAZER"), VECTRA(7, "VECTRA"), VECTRA_GT(7, "VECTRA_GT"), ZAFIRA(7, "ZAFIRA"),
    //CHRYSLER
    C300(8 , "300C"), TOWN_COUNTRY(8,"TOWN&COUNTRY"),
    //CITROEN
    AIRCROSS(9, "AIRCROSS"), C3(9, "C3"), C3_PICASSO(9, "C3_PICASSO"), C4(9, "C4"), C4_LOUNGE(9, "C3_LOUNGE"), C4_PALLAS(9, "C4_PALLAS"), PICASSO(9, "PICASSO"),
    C5(9, "C5"), C5_TOURER(9, "C5_TOURER"), DS3(9, "DS3"), DS5(9, "DS5"), JUMPER(9, "JUMPER"), XSARA_PICASSO(9,"XSARA_PICASSO"),
    //DODGE
    DURANGO(10, "DURANGO"), JOURNEY(10, "JOURNEY"),
    //FERRARI
    F458(11, "458"), CALIFORNIA(11, "CALIFORNIA"), F599_GTO(11,"F599_GTO"),
    //FIAT
    FIAT_500(12, "500"), ABARTH_500(12, "500_ABARTH"), BRAVO(12, "BRAVO"), DOBLO(12, "DOBLO"), DUCATO(12, "DUCATO"), FIAT_MOBI(12, "FIAT_MOBI"), FIAT_TORO(12, "FIAT_TORO"),
    FIORINO(12, "FIORINO"), FREEMONT(12, "FREEMONT"), GRAND_SIENA(12, "GRAND_SIENA"), IDEA(12, "IDEA"), LINEA(12, "LINEA"), MILLE(12, "MILLE"), PALIO(12, "PALIO"),
    PALIO_ADVENTURE(12, "PALIO_ADVENTURE"), PALIO_WEEKEND(12, "PALIO_WEEKEND"), PUNTO(12, "PUNTO"), SIENA_EL(12, "SIENA_EL"), STRADA(12, "STRADA"), UNO(12, "UNO"),
    //FORD
    COURIER(13, "COURIER"), ECOSPORT(13, "ECOSPORT"), EDGE(13, "EDGE"), F250(13, "F-250"), FIESTA_ROCAM(13, "FIESTA_ROCAM"), FOCUS_FASTBACK(13, "FOCUS_FASTBACK"),
    FOCUS_HATCH(13, "FOCUS_HATCH"), FUSION(13, "FUSION"),KA(13, "KA"), FIESTA_HATCH(13, "FIESTA_HATCH"), RANGER(13, "RANGER"), TRANSIT(13, "TRANSIT"),
    //HONDA
    ACCORD(14, "ACCORD"), CR_V(14, "CR-V"), CITY(14, "CITY"), CIVIC(14, "CIVIC"), CIVIC_SI(14, "CIVIC_SI"), FIT(14, "FIT"), HR_V(14, "HR-V"),
    //HYUNDAI
    AZERA(15, "AZERA"), ELANTRA(15, "ELANTRA"), EQUUS(15, "EQUUS"), HB20(15, "HB20"), HB20S(15, "HB20S"), HB20X(15, "HB20X"), HR(15, "HR"), SANTA_FE(15, "SANTA_FE"),
    SONATA(15, "SONATA"), TUCSON(15, "TUCSON"), VELOSTER(15, "VELOSTER"), VERACRUZ(15, "VERACRUZ"), I30(15, "I30"),
    //JAC MOTORS
    JAC(16,"JAC_MOTORS"),
    //JAGUAR
    F_TYPE(17, "F_TYPE"), XF(17, "XF"), XJ_SUPERSPORT(17, "XJ_SUPERSPORT"), XKR(17, "XKR"),
    //JEEP
    CHEROKEE(18, "CHEROKEE"), GRAND_CHEROKEE(18, "GRAND_CHEROKEE"), JEEP_RENEGADE(18, "JEEP_RENEGADE"), WRANGLER(18, "WRANGLER"),
    //JINBEI
    JINBEI(19, "JINBEI"),
    //LAMBO
    GALLARDO(20, "GALLARDO"), AVENTADOR(20, "AVENTADOR"),
    //MAHINDRA
    MAHINDRA(21, "MAHINDRA"),
    //GHIBLI
    GHIBLI(22, "GHIBLI"),
    //MERCEDES-BENZ
    CLA(23, "CLA"), CLASS_A(23, "CLASS_A"), CLASS_B(23, "CLASS_B"), CLASS_C(23, "CLASS_C"), CLASS_CL(23, "CLASS_CL"), AMG(23, "AMG"), CLASS_E(23, "CLASS_E"), CLASS_G(23, "CLASS_G"), SLK(23, "SLK"), 
    //MG_MOTORS
    MG_MOTORS(24, "MG_MOTORS"),
    //MITSUBISHI
    LANCER_EVOLUTION(25, "LANCER_EVOLUTION"), OUTLANDER(25, "OUTLANDER"),
    //NISSAN
    ALTIMA(26, "ALTIMA"), FRONTIER(26, "FRONTIER"), GRAND_LIVINA(26, "GRAND_LIVINA"), TIIDA(26, "TIIDA"), VERSA(26, "VERSA"),
    //PEUGEOT
    P208(27, "208"), P209(27, "209"), P210(27, "210"), P211(27, "211"),
    //PORSCHE
    P_911(28, "Carrera 911"), BOXTER(28, "BOXTER"), CAYENNE(28, "CAYENNE"), CAYMAN(28, "CAYMAN"), PANAMERA(28, "PANAMERA"),
    //RAM
    RAM_2500(29, "2500"),
    //SMART
    SMART(30, "SMART"),
    //SUBARU
    FORESTER(31, "FORESTER"), IMPRESA(31, "IMPRESA"), LEGACY(31, "LEGACY"), OUTBACK(31, "OUTBACK"), TRIBECA(31, "TRIBECA"),
    //TOYOTA
    CAMRY(32, "CAMRY"), COROLLA(32, "COROLLA"), ETIOS(32, "ETIOS"), HILUX(32, "HILUX"), PRIUS(32, "PRIUS"), RAV4(32, "RAV4"),
    //VOLKSWAGEN
    AMAROK(33, "AMAROK"), CROSSFOX(33, "CROSSFOX"), FOX(33, "FOX"), GOLF(33, "GOLF"), JETTA(33, "JETTA"), PASSAT(33, "PASSAT"), POLO(33, "POLO"), TIGUAN(33, "TIGUAN"), TOUAREG(33, "TOUAREG"),
    //VOLVO
    V_C30(34, "VOLVO_C30"), V_S60(34, "V_S60"), V40(34, "V40"), XC60(34, "XC60"), XC90(34,"XC90");
    
    
    private final int    idtipoCarro;
    private final String modeloCarro;
    
    private ModelosCarro(int idtipoCarro, String modeloCarro) {
        this.idtipoCarro = idtipoCarro;
        this.modeloCarro = modeloCarro;
    }
    
    private ModelosCarro(String modeloCarro, int idTipoCarro){
        this.modeloCarro   = modeloCarro;
        this.idtipoCarro = idTipoCarro;
    }
    
    public String getModeloCarro(){
        return modeloCarro;
    }

    public int getIdtipoCarro() {
        return idtipoCarro;
    }
    
    @Override
    public String toString() {
        return modeloCarro;
    }


}
